services:
  - type: web
    name: conf2025
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn conf2025.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: conf2025.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: EMAIL_BACKEND
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_USE_TLS
        sync: false
