# Generated by Django 5.2.3 on 2025-06-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaperSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("abstract", models.TextField()),
                ("pdf", models.FileField(upload_to="papers/")),
                ("main_author_name", models.CharField(max_length=100)),
                ("main_author_email", models.EmailField(max_length=254)),
                ("main_author_phone", models.CharField(max_length=15)),
                ("main_author_affiliation", models.CharField(max_length=255)),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
