# Generated by Django 5.2.3 on 2025-07-15 21:02

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_author", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "abstract_file",
                    models.FileField(
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to="abstracts/",
                    ),
                ),
                (
                    "paper_id",
                    models.CharField(
                        blank=True, editable=False, max_length=15, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "institute",
                    models.CharField(
                        choices=[
                            ("Assam University, Silchar", "Assam University, Silchar"),
                            (
                                "Royal Thimphu College, Bhutan",
                                "Royal Thimphu College, Bhutan",
                            ),
                            ("Others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "custom_institute",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Research Scholar", "Research Scholar"),
                            ("Professor", "Professor"),
                            ("Associate Professor", "Associate Professor"),
                            ("Assistant Professor", "Assistant Professor"),
                            ("Corporate", "Corporate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("keywords", models.TextField()),
                (
                    "full_paper",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to="full_papers/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
                (
                    "mode_of_participation",
                    models.CharField(
                        choices=[("Online", "Online"), ("Offline", "Offline")],
                        default="Offline",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Academician", "Academician"),
                            ("Corporate", "Corporate"),
                            ("Student", "Research Scholar / Student"),
                            ("NonPresenter", "Non-presenter / Listener"),
                            (
                                "International",
                                "International (Non-Indian, Non-Bhutanese)",
                            ),
                        ],
                        default="Student",
                        max_length=30,
                    ),
                ),
                ("payment_amount", models.IntegerField(default=0)),
                ("payment_status", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Abstract Submission",
                "verbose_name_plural": "Abstract Submissions",
                "ordering": ["paper_id"],
            },
        ),
        migrations.CreateModel(
            name="CoAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("affiliation", models.CharField(max_length=200)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Research Scholar", "Research Scholar"),
                            ("Assistant Professor", "Assistant Professor"),
                            ("Associate Professor", "Associate Professor"),
                            ("Professor", "Professor"),
                            ("Corporate", "Corporate"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Academician", "Academician"),
                            ("Corporate", "Corporate"),
                            ("Student", "Research Scholar / Student"),
                            ("NonPresenter", "Non-presenter / Listener"),
                            (
                                "International",
                                "International (Non-Indian, Non-Bhutanese)",
                            ),
                        ],
                        default="Student",
                        max_length=30,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coauthors",
                        to="conference.abstractsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="FinalRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_mode",
                    models.CharField(
                        choices=[("Online", "Online"), ("Offline", "Offline")],
                        max_length=10,
                    ),
                ),
                (
                    "author_identity_proof",
                    models.FileField(
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to="identity_proofs/",
                    ),
                ),
                ("total_amount", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conference.abstractsubmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("affiliation", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[("CoAuthor", "Co-Author"), ("Visitor", "Visitor")],
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("Online", "Online"), ("Offline", "Offline")],
                        max_length=10,
                    ),
                ),
                (
                    "identity_proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to="identity_proofs/",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="conference.finalregistration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_participation_mode",
                    models.CharField(
                        choices=[("Online", "Online"), ("Offline", "Offline")],
                        max_length=10,
                    ),
                ),
                (
                    "author_identity_proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to="identity_proofs/",
                    ),
                ),
                ("total_amount", models.IntegerField(default=0)),
                ("confirmed_on", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conference.abstractsubmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoAuthorParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "participation_mode",
                    models.CharField(
                        choices=[
                            ("None", "Not Attending"),
                            ("Online", "Online"),
                            ("Offline", "Offline"),
                        ],
                        default="None",
                        max_length=10,
                    ),
                ),
                (
                    "identity_proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to="identity_proofs/",
                    ),
                ),
                (
                    "participation_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coauthor_details",
                        to="conference.participationinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("institute", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
