# Generated by Django 5.2.3 on 2025-07-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participationinfo",
            name="submission",
        ),
        migrations.RemoveField(
            model_name="finalparticipant",
            name="affiliation",
        ),
        migrations.RemoveField(
            model_name="finalparticipant",
            name="identity_proof",
        ),
        migrations.RemoveField(
            model_name="finalregistration",
            name="author_identity_proof",
        ),
        migrations.AddField(
            model_name="finalparticipant",
            name="address",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalparticipant",
            name="contact",
            field=models.CharField(default="N/A", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalparticipant",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="N/A",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalparticipant",
            name="id_proof",
            field=models.FileField(blank=True, null=True, upload_to="id_proofs/"),
        ),
        migrations.AddField(
            model_name="finalregistration",
            name="author_address",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalregistration",
            name="author_contact",
            field=models.CharField(default="N/A", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalregistration",
            name="author_designation",
            field=models.CharField(default="N/A", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalregistration",
            name="author_gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="N/A",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalregistration",
            name="author_id_proof",
            field=models.FileField(default="N/A", upload_to="id_proofs/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalregistration",
            name="author_name",
            field=models.CharField(default="N/A", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="finalparticipant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="finalregistration",
            name="total_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="CoAuthorParticipation",
        ),
        migrations.DeleteModel(
            name="ParticipationInfo",
        ),
    ]
