# Generated by Django 5.2.3 on 2025-07-16 09:16

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0002_remove_participationinfo_submission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalregistration",
            name="payment_screenshot",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="payment_screenshots/",
            ),
        ),
        migrations.AddField(
            model_name="finalregistration",
            name="payment_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="finalregistration",
            name="total_amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
