# Generated by Django 5.2.3 on 2025-06-20 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0003_papersubmission_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="papersubmission",
            name="abstract",
        ),
        migrations.RemoveField(
            model_name="papersubmission",
            name="main_author_affiliation",
        ),
        migrations.RemoveField(
            model_name="papersubmission",
            name="main_author_email",
        ),
        migrations.RemoveField(
            model_name="papersubmission",
            name="main_author_name",
        ),
        migrations.RemoveField(
            model_name="papersubmission",
            name="main_author_phone",
        ),
        migrations.RemoveField(
            model_name="papersubmission",
            name="pdf",
        ),
        migrations.AddField(
            model_name="papersubmission",
            name="abstract_file",
            field=models.FileField(null=True, upload_to="abstracts/"),
        ),
        migrations.AddField(
            model_name="papersubmission",
            name="full_paper",
            field=models.FileField(blank=True, null=True, upload_to="full_papers/"),
        ),
        migrations.AddField(
            model_name="papersubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="papersubmission",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
