# Generated by Django 5.2.3 on 2025-07-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0003_finalregistration_payment_screenshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalregistration",
            name="presenter_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
