# Generated by Django 5.2.3 on 2025-06-21 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0004_remove_papersubmission_abstract_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coauthor",
            name="paper",
        ),
        migrations.AlterField(
            model_name="coauthor",
            name="affiliation",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="AbstractSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paper_id",
                    models.CharField(
                        default="", editable=False, max_length=10, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "institute",
                    models.CharField(
                        choices=[
                            ("Assam University, Silchar", "Assam University, Silchar"),
                            (
                                "Royal Thimphu College, Bhutan",
                                "Royal Thimphu College, Bhutan",
                            ),
                            ("Others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "custom_institute",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Research Scholar", "Research Scholar"),
                            ("Professor", "Professor"),
                            ("Associate Professor", "Associate Professor"),
                            ("Assistant Professor", "Assistant Professor"),
                            ("Corporate", "Corporate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("keywords", models.TextField()),
                ("abstract_file", models.FileField(upload_to="abstracts/")),
                (
                    "full_paper",
                    models.FileField(blank=True, null=True, upload_to="papers/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coauthor",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coauthors",
                to="conference.abstractsubmission",
            ),
        ),
    ]
