# Generated by Django 5.2.3 on 2025-07-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0004_finalregistration_presenter_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalparticipant",
            name="affiliation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
