# Generated by Django 5.2.3 on 2025-07-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0005_finalparticipant_affiliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalregistration",
            name="fee_breakdown",
            field=models.TextField(blank=True),
        ),
    ]
