# Generated by Django 5.2.3 on 2025-06-21 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "conference",
            "0005_remove_coauthor_paper_alter_coauthor_affiliation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="coauthor",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coauthors",
                to="conference.abstractsubmission",
            ),
        ),
        migrations.DeleteModel(
            name="PaperSubmission",
        ),
    ]
