# Generated by Django 5.2.3 on 2025-06-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0006_alter_coauthor_submission_delete_papersubmission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abstractsubmission",
            options={
                "ordering": ["-submitted_on"],
                "verbose_name": "Abstract Submission",
                "verbose_name_plural": "Abstract Submissions",
            },
        ),
        migrations.AlterModelOptions(
            name="coauthor",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AddField(
            model_name="abstractsubmission",
            name="title",
            field=models.CharField(default="Untitled", max_length=255),
            preserve_default=False,
        ),
    ]
