# Generated by Django 5.2.3 on 2025-07-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0007_finalregistration_transaction_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalregistration",
            name="selected_theme",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Society, Equity, Transformation & Social Work",
                        "Society, Equity, Transformation & Social Work",
                    ),
                    (
                        "Knowledge, Education & Human Development",
                        "Knowledge, Education & Human Development",
                    ),
                    (
                        "Politics, Governance, Public Policy, and Political Science",
                        "Politics, Governance, Public Policy, and Political Science",
                    ),
                    (
                        "Economy, Technology & Social Impact",
                        "Economy, Technology & Social Impact",
                    ),
                    (
                        "Culture, Identity & Globalization",
                        "Culture, Identity & Globalization",
                    ),
                    (
                        "Environment, Climate & Sustainability",
                        "Environment, Climate & Sustainability",
                    ),
                    (
                        "Business, Commerce and Business Sustainability",
                        "Business, Commerce and Business Sustainability",
                    ),
                    (
                        "General Social Science and Topics Not Falling Under the Above Categories",
                        "General Social Science and Topics Not Falling Under the Above Categories",
                    ),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
