# Generated by Django 5.2.3 on 2025-06-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0007_alter_abstractsubmission_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractsubmission",
            name="category",
            field=models.CharField(
                choices=[
                    ("Academician", "Academician"),
                    ("Corporate", "Corporate"),
                    ("Student", "Research Scholar / Student"),
                    ("NonPresenter", "Non-presenter / Listener"),
                    ("International", "International (Non-Indian, Non-Bhutanese)"),
                ],
                default="Student",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="abstractsubmission",
            name="mode_of_participation",
            field=models.CharField(
                choices=[("Online", "Online"), ("Offline", "Offline")],
                default="Offline",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="abstractsubmission",
            name="payment_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="abstractsubmission",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
    ]
