# Generated by Django 5.2.3 on 2025-07-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0008_finalregistration_selected_theme"),
    ]

    operations = [

            ],
        ),
    ]
