# Generated by Django 5.2.3 on 2025-06-24 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0008_abstractsubmission_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_participation_mode",
                    models.CharField(
                        choices=[("Online", "Online"), ("Offline", "Offline")],
                        max_length=10,
                    ),
                ),
                (
                    "author_identity_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="identity_proofs/"
                    ),
                ),
                ("total_amount", models.IntegerField(default=0)),
                ("confirmed_on", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conference.abstractsubmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoAuthorParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "participation_mode",
                    models.CharField(
                        choices=[
                            ("None", "Not Attending"),
                            ("Online", "Online"),
                            ("Offline", "Offline"),
                        ],
                        default="None",
                        max_length=10,
                    ),
                ),
                (
                    "identity_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="identity_proofs/"
                    ),
                ),
                (
                    "participation_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coauthor_details",
                        to="conference.participationinfo",
                    ),
                ),
            ],
        ),
    ]
