# Generated by Django 5.2.3 on 2025-06-25 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0009_participationinfo_coauthorparticipation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_mode",
                    models.CharField(
                        choices=[("Online", "Online"), ("Offline", "Offline")],
                        max_length=10,
                    ),
                ),
                (
                    "author_identity_proof",
                    models.FileField(upload_to="identity_proofs/"),
                ),
                ("total_amount", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conference.abstractsubmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("affiliation", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[("CoAuthor", "Co-Author"), ("Visitor", "Visitor")],
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("Online", "Online"), ("Offline", "Offline")],
                        max_length=10,
                    ),
                ),
                (
                    "identity_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="identity_proofs/"
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="conference.finalregistration",
                    ),
                ),
            ],
        ),
    ]
