# Generated by Django 5.2.3 on 2025-07-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0009_visitorregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("id_proof", models.FileField(upload_to="visitor_id_proofs/")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="visitorregistration",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="visitorregistration",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="visitorregistration",
            name="number_of_visitors",
        ),
    ]
