# Generated by Django 5.2.3 on 2025-07-19 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0010_visitor_remove_visitorregistration_is_approved_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Visitor",
        ),
        migrations.DeleteModel(
            name="VisitorRegistration",
        ),
    ]
