# Generated by Django 5.2.3 on 2025-07-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0010_finalregistration_finalparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="coauthor",
            name="designation",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Research Scholar", "Research Scholar"),
                    ("Assistant Professor", "Assistant Professor"),
                    ("Associate Professor", "Associate Professor"),
                    ("Professor", "Professor"),
                    ("Corporate", "Corporate"),
                ],
                default=0,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
