# Generated by Django 5.2.3 on 2025-07-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0011_coauthor_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractsubmission",
            name="email",
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="abstractsubmission",
            name="main_author",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
