# Generated by Django 5.2.3 on 2025-07-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0012_abstractsubmission_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abstractsubmission",
            name="paper_id",
            field=models.CharField(
                blank=True, editable=False, max_length=15, unique=True
            ),
        ),
    ]
