# Generated by Django 5.2.3 on 2025-07-20 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0013_remove_visitor_email_remove_visitor_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Visitor",
        ),
    ]
