# Generated by Django 5.2.3 on 2025-07-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0014_delete_visitor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("institution", models.CharField(blank=True, max_length=150)),
                ("num_accompanying", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
