# Generated by Django 5.2.3 on 2025-07-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0015_remove_userprofile_custom_institution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coauthor",
            name="category",
            field=models.CharField(
                choices=[
                    ("Academician", "Academician"),
                    ("Corporate", "Corporate"),
                    ("Student", "Research Scholar / Student"),
                    ("NonPresenter", "Non-presenter / Listener"),
                    ("International", "International (Non-Indian, Non-Bhutanese)"),
                ],
                default="Student",
                max_length=30,
            ),
        ),
    ]
