# Generated by Django 5.2.3 on 2025-07-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0015_visitor"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.CharField(max_length=15)),
                ("address", models.TextField()),
                (
                    "id_proof_type",
                    models.CharField(
                        choices=[("passport", "Passport"), ("voter_id", "Voter ID")],
                        max_length=20,
                        verbose_name="ID Proof Type",
                    ),
                ),
                (
                    "id_proof_file",
                    models.FileField(
                        upload_to="identity_proofs/",
                        verbose_name="Upload ID Proof (PDF, JPG, PNG)",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Visitor",
        ),
    ]
