# Generated by Django 5.2.3 on 2025-07-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0016_visitorregistration_delete_visitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitorregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="visitorregistration",
            name="id_proof_file",
            field=models.FileField(upload_to="identity_proofs/"),
        ),
        migrations.AlterField(
            model_name="visitorregistration",
            name="id_proof_type",
            field=models.CharField(
                choices=[("passport", "Passport"), ("voter_id", "Voter ID")],
                max_length=20,
            ),
        ),
    ]
