# Generated by Django 5.2.3 on 2025-07-20 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0017_visitorregistration_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=15)),
                (
                    "id_proof_type",
                    models.CharField(
                        choices=[("passport", "Passport"), ("voter_id", "Voter ID")],
                        max_length=20,
                    ),
                ),
                ("id_proof_file", models.FileField(upload_to="identity_proofs/")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_visitors",
                        to="conference.visitorregistration",
                    ),
                ),
            ],
        ),
    ]
