# Generated by Django 5.2.3 on 2025-07-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0018_additionalvisitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalregistration",
            name="has_paid",
            field=models.BooleanField(default=False),
        ),
    ]
