# Generated by Django 5.2.3 on 2025-07-22 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0019_finalregistration_has_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finalregistration",
            name="has_paid",
        ),
    ]
