# Generated by Django 5.2.3 on 2025-07-22 18:24

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0020_remove_finalregistration_has_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalregistration",
            name="author_id_proof",
            field=models.FileField(
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="id_proofs/",
            ),
        ),
    ]
